### ISSUE TITLE
Google Sign-in does not work

### ISSUE THREAD

**Issue by cynthia5610** [star4z/planner.go#17]
Sign in does not work

**Comment by star4z** [comment]
It's showing error code 10 which is listed as "Developer Error" https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes.html#public-static-final-int-developer_error

**Comment by star4z** [comment]
Could also be complicated by the fact that the app is signed by Google Play upon upload, so the SHA-1 of the release version is different from the version used in testing.

**Comment by star4z** [comment]
Based on [this](https://github.com/googlesamples/google-services/issues/360) it appears that you need to have 3 API keys for you app: 1 for debug, 1 for release, and 1 for Google Play.

**Comment by star4z** [comment]
When trying to create an OAuth client with the debug build SHA-1, I get the error "Duplicate fingerprint: The fingerprint you specified is already used by an Android OAuth2 client ID in this project or another project"

There are currently old projects that need to expire in order for the debug to work. (Currently, the project with the above-mentioned key is pending deletion.)

**Comment by star4z** [comment]
I un-deleted the appropriate project and now the debug test works again. We shall see with regards to the GP release build.

**Comment by star4z** [comment]
Upon further testing, the updated key in the Google API console means the stable version currently works already!
