### ISSUE TITLE
Weird toolbar animation occurs when adding an item to a ListActivity

### ISSUE THREAD

**Issue by star4z** [star4z/planner.go#32]

**Comment by cynthia5610** [comment]
![71910474_979001505765521_2969783681171849216_n](https://user-images.githubusercontent.com/9850178/65637901-048cff00-dfb3-11e9-9afb-49ea756f6a66.png)
![71287991_506349326579994_2350486316627525632_n](https://user-images.githubusercontent.com/9850178/65637910-06ef5900-dfb3-11e9-8470-d8b816fdc124.png)

**Comment by star4z** [comment]
This appears to be caused by the imm.toggleSoftInput() method call.

**Comment by star4z** [comment]
This seems to be an implication of using android:fitsSystemWindows=true when opening the soft keyboard. The same behavior occurs when using InputMethodManager.showSoftInput() and     dialog.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_VISIBLE);
